export const CATALOG = [{
    id: 1,
    name: 'Название товара',
    description: 'Краткое описание товара со всеми его прелестями',
    img: 'assets/img/item-1.jpg',
    amount: 1,
    total: 8,
    price: 210,
}, {
    id: 2,
    name: 'Название товара',
    description: 'Краткое описание товара со всеми его прелестями',
    img: 'assets/img/item-2.jpg',
    amount: 1,
    total: 6,
    price: 415,
}, {
    id: 3,
    name: 'Название товара',
    description: 'Краткое описание товара со всеми его прелестями',
    img: 'assets/img/item-3.jpg',
    amount: 1,
    total: 5,
    price: 627,
}];